<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Kreiraj</strong> dokument',
    '<strong>ONLYOFFICE Docs</strong> not accessible.' => '<strong>ONLYOFFICE Docs</strong> nije pristupačan.',
    '<strong>ONLYOFFICE Docs</strong> not configured yet.' => '<strong>ONLYOFFICE Docs</strong> još nije konfiguriran.',
    '<strong>ONLYOFFICE Docs</strong> successfully connected! - Installed version: {version}' => '<strong>ONLYOFFICE Docs</strong> uspješno spojen! - Instalirana verzija: {version}',
    '<strong>ONLYOFFICE - Docs</strong> module configuration' => '<strong>ONLYOFFICE - Docs</strong> konfiguracija modula',
    '<strong>Share</strong> document' => '<strong>Dijeli</strong> dokument',
    'Close' => 'Zatvori',
    'Copy to clipboard' => 'Kopiraj u međuspremnik',
    'Could not find requested file!' => 'Traženi dokument nije pronađen!',
    'Could not find shared file!' => 'Dijeljeni dokument nije pronađen!',
    'File read access denied!' => 'Čitanje datoteke - pristup odbijen!',
    'File write access denied!' => 'Pisanje datoteke - pristup odbijen!',
    'Hostname' => 'Hostname',
    'Link for view only access' => 'Poveznica za pristup samo pregledu',
    'Link with enabled write access' => 'Poveznica s omogućenim uređivanjem',
    'Open the new document in the next step' => 'Otvori novi dokument u sljedećem koraku',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Možete jednostavno podijeliti ovaj dokument koristeći direktnu poveznicu (link). Korisnik ne treba registirani račun na platformi.',
    '<strong>Convert</strong> document' => '<strong>Pretvori</strong> dokument',
    '<strong>ONLYOFFICE Docs</strong> invalid JWT token.' => '<strong>ONLYOFFICE Docs</strong> nevažeći JWT token',
    'Convert document' => 'Pretvori dokument',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Pretvaranje <strong>{oldFileName}</strong> u <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Kreiraj dokument <small>(Tekst, Proračunska tablica, Prezentacija)</small>',
    'Done!' => 'Gotovo!',
    'Edit document' => 'Uredi dokument',
    'Error:' => 'Greška:',
    'JWT Secret' => 'JWT Tajna',
    'JWT Secret key (leave blank to disable)' => 'JWT Tajni ključ (ostavite prazno da bi onemogućili)',
    'Share' => 'Podijeli',
    'View document' => 'Pogledaj dokument',
    'e.g. http://documentserver' => 'Npr. http://documentserver',
    'ONLYOFFICE Docs address for internal requests from the server' => 'Adresa pružatelja ONLYOFFICE Docs za interne zahtjeve od strane poslužitelja',
    'Server address for internal requests from ONLYOFFICE Docs' => 'Adresa poslužitelja za interne zahtjeve od strane pružatelja ONLYOFFICE Docs',
    'Can use ONLYOFFICE' => 'Može koristiti ONLYOFFICE',
    'Allows the user to use ONLYOFFICE.' => 'Omogućuje korisniku da upotrebljava ONLYOFFICE.',
    'Disable certificate verification (insecure)' => 'Onemogući verifikaciju certifikata (nesigurno)',
];
