<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Luo</strong> tiedosto',
    '<strong>DocumentServer</strong> not accessible.' => '<strong>DocumentServer</strong> ei yhteyttä.',
    '<strong>DocumentServer</strong> not configured yet.' => '<strong>DocumentServer</strong> ei määritetty.',
    '<strong>DocumentServer</strong> successfully connected! - Installed version: {version}' => '<strong>DocumentServer</strong> yhdistetty! - Versio: {version}',
    '<strong>ONLYOFFICE - DocumentServer</strong> module configuration' => '<strong>OnlyOffice - DocumentServer</strong> laajennuksen määritys',
    '<strong>Share</strong> document' => '<strong>Jaa</strong> tiedosto',
    'Close' => 'Sulje',
    'Copy to clipboard' => 'Kopioi leikepöydälle',
    'Could not find requested file!' => 'Pyydettyä tiedostoa ei löytynyt!',
    'Could not find shared file!' => 'Jaettua tiedostoa ei löytynyt!',
    'File read access denied!' => 'Tiedoston luku estetty!',
    'File write access denied!' => 'Tiedoston muokkaus estetty!',
    'Hostname' => 'Isäntänimi',
    'Link for view only access' => 'Katselu linkki',
    'Link with enabled write access' => 'Linkki jolla voi muokata oikeus',
    'Open the new document in the next step' => 'Avaa tiedosto heti',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Voit jakaa tämän tiedoston tällä linkillä. Käyttäjän ei tarvitse olla palvelun jäsen.',
    'e.g. http://documentserver' => 'esim. http://documentserver',
    '<strong>Convert</strong> document' => '',
    '<strong>DocumentServer</strong> invalid JWT token.' => '',
    'Convert document' => '',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => '',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => '',
    'Done!' => '',
    'Edit document' => '',
    'Error:' => '',
    'JWT Secret' => '',
    'JWT Secret key (leave blank to disable)' => '',
    'Share' => '',
    'View document' => '',
];
