<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Luo</strong> tiedosto',
    '<strong>ONLYOFFICE Docs</strong> not accessible.' => '<strong>ONLYOFFICE Docs</strong> ei yhteyttä.',
    '<strong>ONLYOFFICE Docs</strong> not configured yet.' => '<strong>ONLYOFFICE Docs</strong> ei määritetty.',
    '<strong>ONLYOFFICE Docs</strong> successfully connected! - Installed version: {version}' => '<strong>ONLYOFFICE Docs</strong> yhdistetty! - Versio: {version}',
    '<strong>ONLYOFFICE - Docs</strong> module configuration' => '<strong>ONLYOFFICE - Docs</strong> laajennuksen määritys',
    '<strong>Share</strong> document' => '<strong>Jaa</strong> tiedosto',
    'Close' => 'Sulje',
    'Copy to clipboard' => 'Kopioi leikepöydälle',
    'Could not find requested file!' => 'Pyydettyä tiedostoa ei löytynyt!',
    'Could not find shared file!' => 'Jaettua tiedostoa ei löytynyt!',
    'File read access denied!' => 'Tiedoston luku estetty!',
    'File write access denied!' => 'Tiedoston muokkaus estetty!',
    'Hostname' => 'Isäntänimi',
    'Link for view only access' => 'Katselu linkki',
    'Link with enabled write access' => 'Linkki jolla voi muokata oikeus',
    'Open the new document in the next step' => 'Avaa tiedosto heti',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Voit jakaa tämän tiedoston tällä linkillä. Käyttäjän ei tarvitse olla palvelun jäsen.',
    'e.g. http://documentserver' => 'esim. http://documentserver',
    '<strong>Convert</strong> document' => '<strong>Muunna</strong> tiedosto',
    '<strong>ONLYOFFICE Docs</strong> invalid JWT token.' => '<strong>ONLYOFFICE Docs</strong> virheellinen JWT-tunnus.',
    'Convert document' => 'Muunna tiedosto',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Muunnetaan <strong>{oldFileName}</strong> tiedostoksi <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Tee tiedosto <small>(Teksti, Laskutaulukko, Esitys)</small>',
    'Done!' => 'Tehty!',
    'Edit document' => 'Muokkaa tiedostoa',
    'Error:' => 'Virhe:',
    'JWT Secret' => 'JWT Salaus',
    'JWT Secret key (leave blank to disable)' => 'JWT Salainen avain (tyhjä: pois käytöstä)',
    'Share' => 'Jaa',
    'View document' => 'Tarkasta tiedosto',
    'ONLYOFFICE Docs address for internal requests from the server' => 'ONLYOFFICE Docs osoite palvelimen sisäisille pyynnöille',
    'Server address for internal requests from ONLYOFFICE Docs' => 'Palvelimen osoite ONLYOFFICE Docs sisäisille pyynnöille',
    'Can use ONLYOFFICE' => 'Voi käyttää ONLYOFFICEA',
    'Allows the user to use ONLYOFFICE.' => 'Sallii käyttäjän käyttää ONLYOFFICEA.',
];
