<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>创建</strong>文件',
    '<strong>ONLYOFFICE Docs</strong> not accessible.' => '<strong>ONLYOFFICE Docs</strong>无法访问。',
    '<strong>ONLYOFFICE Docs</strong> not configured yet.' => '<strong>ONLYOFFICE Docs</strong>还没有配置。',
    '<strong>ONLYOFFICE Docs</strong> successfully connected! - Installed version: {version}' => '<strong>ONLYOFFICE Docs</strong>连接成功！- 已安装的版本：{version}',
    '<strong>Share</strong> document' => '共享',
    'Close' => '关闭',
    'Copy to clipboard' => '复制到剪贴板',
    'Could not find requested file!' => '找不到请求的文件！',
    'Could not find shared file!' => '找不到共享的文件！',
    'File read access denied!' => '文件读取权限被拒绝！',
    'File write access denied!' => '文件写入权限被拒绝！',
    'Hostname' => '主机名',
    'Link for view only access' => '仅供查看的链接',
    'Link with enabled write access' => '启用写入权限的链接',
    'Open the new document in the next step' => '在下一步骤中打开新的文件',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => '您可以使用直接链接来分享这份文件。用户不需要在该平台上有一个有效的用户账户。',
    'e.g. http://documentserver' => '例如 http://documentserver',
    '<strong>Convert</strong> document' => '<strong>转换</strong>文件',
    '<strong>ONLYOFFICE Docs</strong> invalid JWT token.' => '<strong>ONLYOFFICE Docs</strong>无效的JWT令牌。',
    '<strong>ONLYOFFICE - Docs</strong> module configuration' => '<strong>ONLYOFFICE - Docs</strong>模块配置',
    'Convert document' => '转换文件',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => '正在将 <strong>{oldFileName}</strong> 转换成 <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => '创建文件</small>（文本文档、电子表格、演示文稿）</small>',
    'Done!' => '完成了！',
    'Edit document' => '编辑文件',
    'Error:' => '错误：',
    'JWT Secret' => 'JWT秘密',
    'JWT Secret key (leave blank to disable)' => 'JWT密匙（留空为禁用）',
    'Share' => '分享',
    'View document' => '查看文件',
    'ONLYOFFICE Docs address for internal requests from the server' => '用于服务器内部的ONLYOFFICE Docs的地址',
    'Server address for internal requests from ONLYOFFICE Docs' => '用于ONLYOFFICE Docs内部请求的服务器的地址',
    'Can use ONLYOFFICE' => '可以使用ONLYOFFICE',
    'Allows the user to use ONLYOFFICE.' => '允许用户使用ONLYOFFICE。',
    'Form template' => '表单模板',
    'Fill in form in ONLYOFFICE' => '在ONLYOFFICE上填写表单',
    'Please update ONLYOFFICE Docs to version 7.0 to work on fillable forms online' => '请将ONLYOFFICE Docs更新到7.0版本，以便在线编辑可填写的表单',
    'Disable certificate verification (insecure)' => '关闭证书校验(不安全)',
    'Not supported version' => '不支持的版本',	
    'The customization section allows personalizing the editor interface'=> '自定义设置区允许对编辑器界面进行个性化设置',
    'Display Chat menu button' => '显示交流菜单按钮',
    'Display the header more compact' => '更紧致的显示菜单栏',
    'Display Feedback & Support menu button' => '显示反馈&支持菜单按钮',
    'Display Help menu button' => '显示帮助菜单按钮',
    'Display monochrome toolbar header' => '显示单色工具栏标题',
    'Error when trying to connect ({error})' => '连接是发生异常 ({error})',
    'Mixed Active Content is not allowed. HTTPS address for ONLYOFFICE Docs is required.' => '不允许混合活动内容，请使用HTTPS连接ONLYOFFICE Docs。',
    'Open the file for editing (due to format restrictions, the data might be lost when saving to the formats from the list below)' => '默认的文件编辑器 (由于文件格式限制，保存为下列格式时，数据可能会缺失)',
    'Connect to demo ONLYOFFICE Docs server' => '连接到 ONLYOFFICE Docs 服务器的演示',
    'This is a public test server, please do not use it for private sensitive data. The server will be available during a 30-day period.' => '这是公开的测试服务器，请勿用于隐私数据。服务器试用期限为30天。',
    'The 30-day test period is over, you can no longer connect to demo ONLYOFFICE Docs server.' => '30天试用期已结束，无法连接ONLYOFFICE Docs 服务器的演示。',
    'Keep intermediate versions when editing (forcesave)' => '编辑时保留中间版本 (强制保存)',
    'Authorization header' => '授权标头',
    'Leave blank to use default header' => '留空以使用默认的标头',
];
