<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Crea</strong> documento',
    '<strong>ONLYOFFICE Docs</strong> not accessible.' => '<strong>ONLYOFFICE Docs</strong> non accessibile.',
    '<strong>ONLYOFFICE Docs</strong> not configured yet.' => '<strong>ONLYOFFICE Docs</strong> non ancora configurato.',
    '<strong>ONLYOFFICE Docs</strong> successfully connected! - Installed version: {version}' => '<strong>ONLYOFFICE Docs</strong> collegato correttamente! - Versione installata: {version}',
    '<strong>ONLYOFFICE - Docs</strong> module configuration' => 'Configurazione modulo <strong>ONLYOFFICE - Docs</strong>',
    '<strong>Share</strong> document' => '<strong>Condividi</strong> documento',
    'Close' => 'Chiudi',
    'Copy to clipboard' => 'Copia negli appunti',
    'Could not find requested file!' => 'Non risesco a trovare il file richiesto!',
    'Could not find shared file!' => 'Non riesco a trovare il file condiviso!',
    'File read access denied!' => 'Accesso al file negato!',
    'File write access denied!' => 'Non posso scrivere sul file!',
    'Hostname' => 'Hostname',
    'Link for view only access' => 'Link per sola visualizzazione',
    'Link with enabled write access' => 'Link per visualizzazione e modifica',
    'Open the new document in the next step' => 'Apri il nuovo documento nel prossimo passaggio',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Puoi semplicemente condividere questo documento con un link diretto. L\'utente non necessita di un account valido nella piattaforma.',
    'e.g. http://documentserver' => 'es. http://documentserver',
    '<strong>Convert</strong> document' => '<strong>Converti</strong> documento',
    '<strong>ONLYOFFICE Docs</strong> invalid JWT token.' => '<strong>ONLYOFFICE Docs</strong> JWT non valido.',
    'Convert document' => 'Converti documento',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Conversione di <strong>{oldFileName}</strong> a <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Crea documento <small>(Testo, Foglio di calcolo, Presentazione)</small>',
    'Done!' => 'Fatto!',
    'Edit document' => 'Modifica documento',
    'Error:' => 'Errore:',
    'JWT Secret' => 'Segreto JWT',
    'JWT Secret key (leave blank to disable)' => 'Chiave segreta JWT (lasciare vuoto per disabilitare)',
    'Share' => 'Condividi',
    'View document' => 'Vedere il documento',
    'ONLYOFFICE Docs address for internal requests from the server' => 'Indirizzo di ONLYOFFICE Docs per le richieste interne del server',
    'Server address for internal requests from ONLYOFFICE Docs' => 'Indirizzo del server per le richieste interne da ONLYOFFICE Docs',
    'Can use ONLYOFFICE' => 'Può usare ONLYOFFICE',
    'Allows the user to use ONLYOFFICE.' => 'Permette all\'utente di usare ONLYOFFICE.',
    'Form template' => 'Modello di modulo',
    'Fill in form in ONLYOFFICE' => 'Compilare il modulo in ONLYOFFICE',
    'Please update ONLYOFFICE Docs to version 7.0 to work on fillable forms online' => 'Si prega di aggiornare ONLYOFFICE Docs alla versione 7.0 per lavorare su moduli compilabili online',
    'Disable certificate verification (insecure)' => 'Disattiva la verifica del certificato (non sicuro)',
    'The customization section allows personalizing the editor interface'=> 'La sezione di personalizzazione permette di personalizzare l\'interfaccia dell\'editor',
    'Display Chat menu button' => 'Pulsante del menu Mostra chat',
    'Display the header more compact' => 'Mostra l\'intestazione più compatta',
    'Display Feedback & Support menu button' => 'Pulsante del menu Mostra feedback e supporto',
    'Display Help menu button' => 'Pulsante del menu Mostra guida',
    'Display monochrome toolbar header' => 'Visualizza intestazione della barra degli strumenti monocromatica',
    'Error when trying to connect ({error})' => 'Errore durante il tentativo di connessione ({error})',
    'Mixed Active Content is not allowed. HTTPS address for ONLYOFFICE Docs is required.' => 'Il contenuto attivo misto non è consentito. È richiesto l\'indirizzo HTTPS per ONLYOFFICE Docs.',
    'Keep intermediate versions when editing (forcesave)' => 'Mantieni le versioni intermedie durante la modifica (forzare salvataggio)',
];
