<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Crea</strong> documento',
    '<strong>DocumentServer</strong> not accessible.' => '<strong>DocumentServer</strong> non accessibile.',
    '<strong>DocumentServer</strong> not configured yet.' => '<strong>DocumentServer</strong> non ancora configurato.',
    '<strong>DocumentServer</strong> successfully connected! - Installed version: {version}' => '<strong>DocumentServer</strong> collegato correttamente! - Versione installata: {version}',
    '<strong>ONLYOFFICE - DocumentServer</strong> module configuration' => 'Configurazione modulo <strong>ONLYOFFICE - DocumentServer</strong>',
    '<strong>Share</strong> document' => '<strong>Condividi</strong> documento',
    'Close' => 'Chiudi',
    'Copy to clipboard' => 'Copia negli appunti',
    'Could not find requested file!' => 'Non risesco a trovare il file richiesto!',
    'Could not find shared file!' => 'Non riesco a trovare il file condiviso!',
    'File read access denied!' => 'Accesso al file negato!',
    'File write access denied!' => 'Non posso scrivere sul file!',
    'Hostname' => 'Hostname',
    'Link for view only access' => 'Link per sola visualizzazione',
    'Link with enabled write access' => 'Link per visualizzazione e modifica',
    'Open the new document in the next step' => 'Apri il nuovo documento nel prossimo passaggio',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Puoi semplicemente condividere questo documento con un link diretto. L\'utente non necessita di un account valido nella piattaforma.',
    'e.g. http://documentserver' => 'es. http://documentserver',
    '<strong>Convert</strong> document' => '<strong>Converti</strong> documento',
    '<strong>DocumentServer</strong> invalid JWT token.' => '<strong>DocumentServer</strong> JWT non valido.',
    'Convert document' => 'Converti documento',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Conversione di <strong>{oldFileName}</strong> a <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Crea documento <small>(Testo, Foglio di calcolo, Presentazione)</small>',
    'Done!' => 'Fatto!',
    'Edit document' => 'Modifica documento',
    'Error:' => 'Errore:',
    'JWT Secret' => 'Segreto JWT',
    'JWT Secret key (leave blank to disable)' => 'Chiave segreta JWT (lasciare vuoto per disabilitare)',
    'Share' => 'Condividi',
    'View document' => 'Vedere il documento',
];
