<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Создать</strong> документ ',
    '<strong>ONLYOFFICE Docs</strong> not accessible.' => '<strong>ONLYOFFICE Docs</strong> недоступен.',
    '<strong>ONLYOFFICE Docs</strong> not configured yet.' => '<strong>ONLYOFFICE Docs</strong> еще не настроен.',
    '<strong>ONLYOFFICE Docs</strong> successfully connected! - Installed version: {version}' => '<strong>ONLYOFFICE Docs</strong> успешно подключен! – Установленная версия: {version}',
    '<strong>ONLYOFFICE - Docs</strong> module configuration' => 'Настройка модуля <strong>ONLYOFFICE – Docs</strong>',
    '<strong>Share</strong> document' => '<strong>Предоставить доступ</strong> к документу',
    'Close' => 'Закрыть',
    'Copy to clipboard' => 'Скопировать в буфер обмена',
    'Could not find requested file!' => 'Запрашиваемый файл не найден!',
    'Could not find shared file!' => 'Совместно используемый файл не найден!',
    'File read access denied!' => 'Доступ к файлу на чтение запрещен!',
    'File write access denied!' => 'Доступ к файлу на запись запрещен!',
    'Hostname' => 'Имя хоста',
    'Link for view only access' => 'Ссылка только для просмотра',
    'Link with enabled write access' => 'Ссылка с включенным доступом на запись',
    'Open the new document in the next step' => 'Открыть новый документ на следующем шаге',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Вы можете просто предоставить доступ к этому документу по прямой ссылке. Пользователю не требуется действительный аккаунт на этой платформе.',
    'e.g. http://documentserver' => 'например, http://documentserver',
    '<strong>Convert</strong> document' => '<strong>Конвертировать</strong> документ',
    '<strong>ONLYOFFICE Docs</strong> invalid JWT token.' => 'Недопустимый JWT-токен <strong>ONLYOFFICE Docs</strong>.',
    'Convert document' => 'Конвертировать документ',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Конвертация <strong>{oldFileName}</strong> в <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation, Form template)</small>' => 'Создать документ <small>(Текстовый, Таблица, Презентация, Шаблон формы)</small>',
    'Done!' => 'Готово!',
    'Edit document' => 'Редактировать документ',
    'Error:' => 'Ошибка:',
    'JWT Secret' => 'Секретный ключ JWT',
    'JWT Secret key (leave blank to disable)' => 'Секретный ключ JWT (оставьте пустым для отключения)',
    'Share' => 'Предоставить доступ',
    'View document' => 'Просмотреть документ',
    'ONLYOFFICE Docs address for internal requests from the server' => 'Адрес ONLYOFFICE Docs для внутренних запросов сервера',
    'Server address for internal requests from ONLYOFFICE Docs' => 'Адрес сервера для внутренних запросов ONLYOFFICE Docs',
    'Can use ONLYOFFICE' => 'Можно использовать ONLYOFFICE',
    'Allows the user to use ONLYOFFICE.' => 'Позволяет пользователю использовать ONLYOFFICE.',
    'Form template' => 'Шаблон формы',
    'Fill in form in ONLYOFFICE' => 'Заполнить форму в ONLYOFFICE',
    'Please update ONLYOFFICE Docs to version 7.0 to work on fillable forms online' => 'Обновите сервер ONLYOFFICE Docs до версии 7.0 для работы с формами онлайн',
    'Disable certificate verification (insecure)' => 'Отключить проверку сертификата (небезопасно)',
    'Not supported version' => 'Неподдерживаемая версия',
    'The customization section allows personalizing the editor interface' => 'Раздел настройки позволяет изменить интерфейс редактора',
    'Display Chat menu button' => 'Отображать кнопку чата',
    'Display the header more compact' => 'Отображать заголовок компактным',
    'Display Feedback & Support menu button' => 'Отображать кнопку Обратной связи и поддержки',
    'Display Help menu button' => 'Отображать кнопку справки',
    'Display monochrome toolbar header' => 'Отображать монохромный заголовок панели инструментов',
    'Error when trying to connect ({error})' => 'При попытке соединения возникла ошибка ({error})',
    'Mixed Active Content is not allowed. HTTPS address for ONLYOFFICE Docs is required.' => 'Смешанное активное содержимое запрещено. Для ONLYOFFICE Docs необходимо использовать HTTPS-адрес.',
    'Open the file for editing (due to format restrictions, the data might be lost when saving to the formats from the list below)' => 'Открыть файл на редактирование (из-за ограничений формата данные могут быть утеряны при сохранении в форматы из списка ниже)',
];
