<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Создать</strong> документ ',
    '<strong>DocumentServer</strong> not accessible.' => '<strong>DocumentServer</strong> недоступен.',
    '<strong>DocumentServer</strong> not configured yet.' => '<strong>DocumentServer</strong> еще не настроен.',
    '<strong>DocumentServer</strong> successfully connected! - Installed version: {version}' => '<strong>DocumentServer</strong> успешно подключен! – Установленная версия: {version}',
    '<strong>ONLYOFFICE - DocumentServer</strong> module configuration' => 'Настройка модуля <strong>ONLYOFFICE – DocumentServer</strong>',
    '<strong>Share</strong> document' => '<strong>Предоставить доступ</strong> к документу',
    'Close' => 'Закрыть',
    'Copy to clipboard' => 'Скопировать в буфер обмена',
    'Could not find requested file!' => 'Запрашиваемый файл не найден!',
    'Could not find shared file!' => 'Совместно используемый файл не найден!',
    'File read access denied!' => 'Доступ к файлу на чтение запрещен!',
    'File write access denied!' => 'Доступ к файлу на запись запрещен!',
    'Hostname' => 'Имя хоста',
    'Link for view only access' => 'Ссылка только для просмотра',
    'Link with enabled write access' => 'Ссылка с включенным доступом на запись',
    'Open the new document in the next step' => 'Открыть новый документ на следующем шаге',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Вы можете просто предоставить доступ к этому документу по прямой ссылке. Пользователю не требуется действительный аккаунт на этой платформе.',
    'e.g. http://documentserver' => 'например, http://documentserver',
    '<strong>Convert</strong> document' => '<strong>Конвертировать</strong> документ',
    '<strong>DocumentServer</strong> invalid JWT token.' => 'Недопустимый JWT-токен <strong>DocumentServer</strong>.',
    'Convert document' => 'Конвертировать документ',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Конвертация <strong>{oldFileName}</strong> в <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Создать документ <small>(Текстовый, Таблица, Презентация)</small>',
    'Done!' => 'Готово!',
    'Edit document' => 'Редактировать документ',
    'Error:' => 'Ошибка:',
    'JWT Secret' => 'Секретный ключ JWT',
    'JWT Secret key (leave blank to disable)' => 'Секретный ключ JWT (оставьте пустым для отключения)',
    'Share' => 'Предоставить доступ',
    'View document' => 'Просмотреть документ',
    'Document Editing Service address for internal requests from the server' => 'Адрес службы редактирования документов для внутренних запросов сервера',
    'Server address for internal requests from the Document Editing Service' => 'Адрес сервера для внутренних запросов службы редактирования документов',
    'Can use ONLYOFFICE' => 'Можно использовать ONLYOFFICE',
    'Allows the user to use ONLYOFFICE.' => 'Позволяет пользователю использовать ONLYOFFICE.',
];
