<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Crear</strong> documento',
    '<strong>ONLYOFFICE Docs</strong> not accessible.' => '<strong>ONLYOFFICE Docs</strong> no está accesible.',
    '<strong>ONLYOFFICE Docs</strong> not configured yet.' => '<strong>ONLYOFFICE Docs</strong> no está configurado todavía.',
    '<strong>ONLYOFFICE Docs</strong> successfully connected! - Installed version: {version}' => '¡<strong>ONLYOFFICE Docs</strong> se conectó correctamente! - Versión instalada: {version}',
    '<strong>ONLYOFFICE - Docs</strong> module configuration' => 'Configuración del módulo de <strong>ONLYOFFICE - Docs</strong>',
    '<strong>Share</strong> document' => '<strong>Compartir</strong> documento',
    'Close' => 'Cerrar',
    'Copy to clipboard' => 'Copiar al portapapeles',
    'Could not find requested file!' => '¡No se pudo encontrar el archivo solicitado!',
    'Could not find shared file!' => '¡No se pudo encontrar el archivo compartido!',
    'File read access denied!' => '¡Acceso de lectura al archivo denegado!',
    'File write access denied!' => '¡Acceso de escritura al archivo denegado!',
    'Hostname' => 'Nombre de host',
    'Link for view only access' => 'Enlace para acceso de sólo visualización',
    'Link with enabled write access' => 'Enlace con acceso de escritura habilitado',
    'Open the new document in the next step' => 'Abrir el nuevo documento en el siguiente paso',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Simplemente se puede compartir este documento mediante un enlace directo. El usuario no necesita una cuenta de usuario válida en la plataforma.',
    'e.g. http://documentserver' => 'por ejemplo, http://documentserver',
    '<strong>Convert</strong> document' => '<strong>Convertir</strong> documento',
    '<strong>ONLYOFFICE Docs</strong> invalid JWT token.' => 'Token JWT no válido de <strong>ONLYOFFICE Docs</strong>',
    'Convert document' => 'Convertir documento',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Convirtiendo <strong>{oldFileName}</strong> en <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Crear documento <small>(Texto, Hoja de Cálculo, Presentación)</small>',
    'Done!' => '¡Hecho!',
    'Edit document' => 'Editar documento',
    'Error:' => 'Error:',
    'JWT Secret' => 'Secreto JWT',
    'JWT Secret key (leave blank to disable)' => 'Clave secreta JWT (deje en blanco o desactive)',
    'Share' => 'Compartir',
    'View document' => 'Visualizar documento',
    'ONLYOFFICE Docs address for internal requests from the server' => 'Dirección de ONLYOFFICE Docs para solicitudes internas del servidor',
    'Server address for internal requests from ONLYOFFICE Docs' => 'Dirección de servidor para solicitudes internas del ONLYOFFICE Docs',
    'Can use ONLYOFFICE' => 'Puede utilizar ONLYOFFICE',
    'Allows the user to use ONLYOFFICE.' => 'Permite al usuario utilizar ONLYOFFICE.',
    'Form template' => 'Plantilla de formulario',
    'Fill in form in ONLYOFFICE' => 'Rellenar el formulario en ONLYOFFICE',
    'Please update ONLYOFFICE Docs to version 7.0 to work on fillable forms online' => 'Por favor, actualice ONLYOFFICE Docs a la versión 7.0 para poder trabajar con formularios rellenables en línea',
    'Disable certificate verification (insecure)' => 'Desactivar la verificación de certificados (inseguro)',
    'Not supported version' => 'Versión no compatible',
    'The customization section allows personalizing the editor interface'=> 'La sección de personalización permite customizar la interfaz del editor',
    'Display Chat menu button' => 'Mostrar el botón de Chat',
    'Display the header more compact' => 'Mostrar el encabezado más compacto',
    'Display Feedback & Support menu button' => 'Mostrar el botón de Feedback y Soporte',
    'Display Help menu button' => 'Mostrar el botón de Ayuda',
    'Display monochrome toolbar header' => 'Mostrar el encabezado monocromático de la barra de herramientas',
    'Error when trying to connect ({error})' => 'Error al intentar establecer la conexión ({error})',
    'Mixed Active Content is not allowed. HTTPS address for ONLYOFFICE Docs is required.' => 'Contenido Mixto Activo no está permitido. Se requiere la dirección HTTPS para ONLYOFFICE Docs.',
    'Open the file for editing (due to format restrictions, the data might be lost when saving to the formats from the list below)' => 'Abrir archivo para editar (debido a las restricciones de formato los datos podrían perderse al guardar en los formatos de la siguiente lista)',
    'Connect to demo ONLYOFFICE Docs server' => 'Conectarse al servidor de ONLYOFFICE Docs de demostración',
    'This is a public test server, please do not use it for private sensitive data. The server will be available during a 30-day period.'=> 'Este es un servidor de pruebas público, por favor no lo uses para tus datos confidenciales. El servidor estará disponible durante un período de 30 días.',
    'The 30-day test period is over, you can no longer connect to demo ONLYOFFICE Docs server.' => 'El período de prueba de 30 días ha terminado, ya no puedes conectarte al servidor de ONLYOFFICE Docs de demostración',
    'Keep intermediate versions when editing (forcesave)' => 'Mantener las versiones intermedias durante la edición (forzar guardar)',
    'Authorization header' => 'Encabezado de autenticación',
    'Leave blank to use default header' => 'Dejar en blanco para utilizar el encabezado predeterminado',
];
