<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '文書を<strong>作成する</strong>',
    '<strong>ONLYOFFICE Docs</strong> not accessible.' => '<strong>ONLYOFFICE Docs</strong>にアクセスできません',
    '<strong>ONLYOFFICE Docs</strong> not configured yet.' => '<strong>ONLYOFFICE Docs</strong>が未設定です',
    '<strong>ONLYOFFICE Docs</strong> successfully connected! - Installed version: {version}' => '<strong>ONLYOFFICE Docs</strong>にアクセスしました、バージョンは {version} です',
    '<strong>Share</strong> document' => '文書を<strong>共有する</strong>',
    'Close' => '閉じる',
    'Copy to clipboard' => 'クリップボードにコピーする',
    'Could not find requested file!' => '要求されたファイルが見つかりませんでした',
    'Could not find shared file!' => '共有されたファイルが見つかりませんでした',
    'File read access denied!' => 'ファイル読込みアクセスが拒否されました',
    'File write access denied!' => 'ファイル書込みアクセス拒否がされました',
    'Hostname' => 'ホスト名',
    'Link for view only access' => 'ファイル読み込みアクセス権のリンク',
    'Link with enabled write access' => 'ファイル書き込みアクセス権のリンク',
    'Open the new document in the next step' => '次に、新しい文書を開いてください',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => '直接リンクを使用して文書共有できます。受信側はプラットホームで有効なユーザーアカウントを持っている必要ではありません。',
    'e.g. http://documentserver' => '例えば、http://documentserver',
    '<strong>Convert</strong> document' => '文書を<strong>変換する</strong>',
    '<strong>ONLYOFFICE Docs</strong> invalid JWT token.' => '<strong>ONLYOFFICE Docs</strong>　無効なJWTトークン',
    '<strong>ONLYOFFICE - Docs</strong> module configuration' => '<strong>ONLYOFFICE - Docs</strong>のモジュール構成',
    'Convert document' => '文書を変換する',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => '<strong>{oldFileName}</strong> を<strong>{newFileName}</strong>に変換する',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => '文書を作成する<small>（テキスト・スプレッドシート・プレゼンテーション）</small>',
    'Done!' => '完遂した！',
    'Edit document' => '文書を編集する',
    'Error:' => 'エラー',
    'JWT Secret' => 'JWT秘密',
    'JWT Secret key (leave blank to disable)' => 'JWT秘密鍵（無効するには、ブランクにしておいてください）',
    'Share' => '共有する',
    'View document' => '文書を表示する',
    'ONLYOFFICE Docs address for internal requests from the server' => 'サーバーからの内部リクエストにはONLYOFFICE Docs アドレス',
    'Server address for internal requests from ONLYOFFICE Docs' => 'ONLYOFFICE Docsからの内部リクエストにはサーバーアドレス',
    'Can use ONLYOFFICE' => 'ONLYOFFICEを使用できる',
    'Allows the user to use ONLYOFFICE.' => 'ユーザーがONLYOFFICEを使用できるようにします。',
    'Fill in form in ONLYOFFICE' => 'ONLYOFFICEでフォームを記入する',
    'Please update ONLYOFFICE Docs to version 7.0 to work on fillable forms online' => 'オンラインで入力可能なフォームを作成するには、ONLYOFFICE Docs 7.0版まで更新してください',
    'Disable certificate verification (insecure)' => '証明書の検証を無効にする（安全でない',
    'Not supported version' => 'サポートされていないバージョン',	
    'The customization section allows personalizing the editor interface'=> 'カスタマイズセクションでは、エディターインターフェイスをパーソナライズできます',
    'Display Chat menu button' => 'チャットメニューホタンを表示',
    'Display the header more compact' => 'ヘッダーをよりコンパクトに表示',
    'Display Feedback & Support menu button' => 'フィードバックとサポートメニューホタンを表示',
    'Display Help menu button' => 'ヘルプメニューホタンを表示',
    'Display monochrome toolbar header' => 'モノクローム・ツールバーヘッダーを表示する',
    'Error when trying to connect ({error})' => '接続時にエラーが発生しました ({error})',
    'Mixed Active Content is not allowed. HTTPS address for ONLYOFFICE Docs is required.' => 'アクティブコンテンツの混在は許可されていません。ONLYOFFICE DocsにはHTTPSアドレスが必要です',
    'Open the file for editing (due to format restrictions, the data might be lost when saving to the formats from the list below)' => '編集できるファイルフォーマット (フォーマットの制限により、以下のフォーマットを保存する時にデータが失われる可能性があります)',
    'Connect to demo ONLYOFFICE Docs server' => 'ONLYOFFICE Docsのデモサーバーに接続する',
    'This is a public test server, please do not use it for private sensitive data. The server will be available during a 30-day period.' => 'これはパブリックテストサーバーです。プライベートな機密データには使用しないでください。サーバーを30日間、利用できます。',
    'The 30-day test period is over, you can no longer connect to demo ONLYOFFICE Docs server.' => '30日間のテスト期間が終了したら、ONLYOFFICE Docs デモサーバーには繋がらなくなります。',
    'Keep intermediate versions when editing (forcesave)' => '編集時に、中間バージョンを保持する (強制保存)',
];
