<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => 'ドキュメント類を作成する',
    '<strong>DocumentServer</strong> not accessible.' => 'ドキュメントサーバーにアクセスできません',
    '<strong>DocumentServer</strong> not configured yet.' => 'ドキュメントサーバーが未設定です',
    '<strong>DocumentServer</strong> successfully connected! - Installed version: {version}' => 'ドキュメントサーバーにアクセスしました、バージョンは {version} です',
    '<strong>Share</strong> document' => 'ドキュメント類をシェアする',
    'Close' => '閉じる',
    'Copy to clipboard' => 'クリップボードにコピー',
    'Could not find requested file!' => 'お探しのファイルが見つかりませんでした',
    'Could not find shared file!' => '共有ファイルは見つかりませんでした',
    'File read access denied!' => 'ファイルの読み込みが拒否されました',
    'File write access denied!' => 'ファイルへの書込が拒否されました',
    '<strong>Convert</strong> document' => '',
    '<strong>DocumentServer</strong> invalid JWT token.' => '',
    '<strong>OnlyOffice - DocumentServer</strong> module configuration' => '',
    'Convert document' => '',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => '',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => '',
    'Done!' => '',
    'Edit document' => '',
    'Error:' => '',
    'Hostname' => '',
    'JWT Secret' => '',
    'JWT Secret key (leave blank to disable)' => '',
    'Link for view only access' => '',
    'Link with enabled write access' => '',
    'Open the new document in the next step' => '',
    'Share' => '',
    'View document' => '',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => '',
    'e.g. http://documentserver' => '',
];
