<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '文書を<strong>作成する</strong>',
    '<strong>DocumentServer</strong> not accessible.' => '<strong>ドキュメントサーバー</strong>にアクセスできません',
    '<strong>DocumentServer</strong> not configured yet.' => '<strong>ドキュメントサーバー</strong>が未設定です',
    '<strong>DocumentServer</strong> successfully connected! - Installed version: {version}' => '<strong>ドキュメントサーバー</strong>にアクセスしました、バージョンは {version} です',
    '<strong>Share</strong> document' => '文書を<strong>共有する</strong>',
    'Close' => '閉じる',
    'Copy to clipboard' => 'クリップボードにコピーする',
    'Could not find requested file!' => '要求されたファイルが見つかりませんでした',
    'Could not find shared file!' => '共有されたファイルが見つかりませんでした',
    'File read access denied!' => 'ファイル読込みアクセスが拒否されました',
    'File write access denied!' => 'ファイル書込みアクセス拒否がされました',
    '<strong>Convert</strong> document' => '文書を<strong>変換する</strong>',
    '<strong>DocumentServer</strong> invalid JWT token.' => '<strong>ドキュメントサーバー</strong>　無効なJWTトークン',
    '<strong>ONLYOFFICE - DocumentServer</strong> module configuration' => '<strong>ONLYOFFICEドキュメントサーバー</strong>のモジュール構成',
    'Convert document' => '文書を変換する',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => '<strong>{oldFileName}</strong> を<strong>{newFileName}</strong>に変換する',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => '文書を作成する<small>（テキスト・スプレッドシート・プレゼンテーション）</small>',
    'Done!' => '完遂した！',
    'Edit document' => '文書を編集する',
    'Error:' => 'エラー',
    'Hostname' => 'ホスト名',
    'JWT Secret' => 'JWT秘密',
    'JWT Secret key (leave blank to disable)' => 'JWT秘密鍵（無効するには、ブランクにしておいてください）',
    'Link for view only access' => 'ファイル読み込みアクセス権のリンク',
    'Link with enabled write access' => 'ファイル書き込みアクセス権のリンク',
    'Open the new document in the next step' => '次に、新しい文書を開いてください',
    'Share' => '共有する',
    'View document' => '文書を表示する',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => '直接リンクを使用して文書共有できます。受信側はプラットホームで有効なユーザーアカウントを持っている必要ではありません。',
    'e.g. http://documentserver' => '例えば、http://documentserver',
];
