<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Créer</strong> un document',
    '<strong>ONLYOFFICE Docs</strong> not accessible.' => '<strong>ONLYOFFICE Docs</strong> non accessible.',
    '<strong>ONLYOFFICE Docs</strong> not configured yet.' => '<strong>ONLYOFFICE Docs</strong> pas encore configuré.',
    '<strong>ONLYOFFICE Docs</strong> successfully connected! - Installed version: {version}' => '<strong>ONLYOFFICE Docs</strong> connecté avec succès ! - Version installée : {version}',
    '<strong>ONLYOFFICE - Docs</strong> module configuration' => '<strong>ONLYOFFICE - Docs</strong> configuration du module',
    '<strong>Share</strong> document' => '<strong>Partager</strong> un document',
    'Close' => 'Fermer',
    'Copy to clipboard' => 'Copier dans le presse-papier',
    'Could not find requested file!' => 'Impossible de trouver le fichier demandé !',
    'Could not find shared file!' => 'Impossible de trouver le fichier partagé !',
    'File read access denied!' => 'Lecture du fichier refusée !',
    'File write access denied!' => 'Écriture du fichier refusée !',
    'Hostname' => 'Nom du serveur',
    'Link for view only access' => 'Lien pour un accès uniquement en lecture',
    'Link with enabled write access' => 'Lien avec accès en écriture',
    'Open the new document in the next step' => 'Ouvrir le nouveau document lors de la prochaine étape',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Vous pouvez simplement partager ce document à l\'aide d\'un lien direct. L\'utilisateur n\'a pas besoin de posséder une compte valide sur la plateforme. ',
    'e.g. http://documentserver' => 'par ex. http://documentserver',
    '<strong>Convert</strong> document' => '<strong>Convertir</strong> un document',
    '<strong>ONLYOFFICE Docs</strong> invalid JWT token.' => '<strong>ONLYOFFICE Docs</strong> le jeton JWT n’est pas valide.',
    'Convert document' => 'Convertir un document',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Conversion du <strong>{oldFileName}</strong> en <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Créer un document <small>(Document, Classeur, Présentation)</small>',
    'Done!' => 'Fait !',
    'Edit document' => 'Modifier le document',
    'Error:' => 'Erreur',
    'JWT Secret' => 'JWT Secret',
    'JWT Secret key (leave blank to disable)' => 'JWT clé secrète (laisser en blanc pour désactiver)',
    'Share' => 'Partager',
    'View document' => 'Voir un document',
    'ONLYOFFICE Docs address for internal requests from the server' => 'Adresse du ONLYOFFICE Docs pour les demandes internes du serveur',
    'Server address for internal requests from ONLYOFFICE Docs' => 'Adresse du serveur pour les demandes internes du ONLYOFFICE Docs',
    'Can use ONLYOFFICE' => 'Peut utiliser ONLYOFFICE',
    'Allows the user to use ONLYOFFICE.' => 'Permet à l\'utilisateur d\'utiliser ONLYOFFICE.',
    'Form template' => 'Modèle de formulaire',
    'Fill in form in ONLYOFFICE' => 'Remplir le formulaire dans ONLYOFFICE',
    'Please update ONLYOFFICE Docs to version 7.0 to work on fillable forms online' => 'Veuillez mettre à jour ONLYOFFICE Docs vers la version 7.0 pour travailler sur les formulaires à remplir en ligne',
    'Disable certificate verification (insecure)' => 'Désactiver la vérification du certificat (non sur)',
    'The customization section allows personalizing the editor interface' => 'La section de personnalisation permet de personnaliser l\'interface de l\'éditeur',
    'Display Chat menu button' => 'Afficher le bouton du menu du chat',
    'Display the header more compact' => 'Afficher l\'en-tête plus compact',
    'Display Feedback & Support menu button' => 'Afficher le bouton du menu Feedback & Support',
    'Display Help menu button' => 'Afficher le bouton du menu Aide',
    'Display monochrome toolbar header' => 'Afficher un en-tête monochrome de la barre d\'outils',
    'Error when trying to connect ({error})' => 'Erreur durant la tentative de connexion ({error})',
    'Mixed Active Content is not allowed. HTTPS address for ONLYOFFICE Docs is required.' => 'Le contenu mixte actif n\'est pas autorisé. Une adresse HTTPS pour le ONLYOFFICE Docs est requise',
    'Open the file for editing (due to format restrictions, the data might be lost when saving to the formats from the list below)' => 'Ouvrir le fichier pour édition (en raison de restrictions de format, des données peuvent être perdues lors de l\'enregistrement dans les formats de la liste ci-dessous)',
];
