<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Créer</strong> un document',
    '<strong>DocumentServer</strong> not accessible.' => '<strong>DocumentServer</strong> non accessible.',
    '<strong>DocumentServer</strong> not configured yet.' => '<strong>DocumentServer</strong> pas encore configuré.',
    '<strong>DocumentServer</strong> successfully connected! - Installed version: {version}' => '<strong>DocumentServer</strong> connecté avec succès ! - Version installée : {version}',
    '<strong>ONLYOFFICE - DocumentServer</strong> module configuration' => '<strong>ONLYOFFICE - DocumentServer</strong> configuration du module',
    '<strong>Share</strong> document' => '<strong>Partager</strong> un document',
    'Close' => 'Fermer',
    'Copy to clipboard' => 'Copier dans le presse-papier',
    'Could not find requested file!' => 'Impossible de trouver le fichier demandé !',
    'Could not find shared file!' => 'Impossible de trouver le fichier partagé !',
    'File read access denied!' => 'Lecture du fichier refusée !',
    'File write access denied!' => 'Écriture du fichier refusée !',
    'Hostname' => 'Nom du serveur',
    'Link for view only access' => 'Lien pour un accès uniquement en lecture',
    'Link with enabled write access' => 'Lien avec accès en écriture',
    'Open the new document in the next step' => 'Ouvrir le nouveau document lors de la prochaine étape',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Vous pouvez simplement partager ce document à l\'aide d\'un lien direct. L\'utilisateur n\'a pas besoin de posséder une compte valide sur la plateforme. ',
    'e.g. http://documentserver' => 'par ex. http://documentserver',
    '<strong>Convert</strong> document' => '<strong>Convertir</strong> un document',
    '<strong>DocumentServer</strong> invalid JWT token.' => '<strong>DocumentServer</strong> le jeton JWT n’est pas valide.',
    'Convert document' => 'Convertir un document',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Conversion du <strong>{oldFileName}</strong> en <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Créer un document <small>(Document, Classeur, Présentation)</small>',
    'Done!' => 'Fait !',
    'Edit document' => 'Modifier le document',
    'Error:' => 'Erreur',
    'JWT Secret' => 'JWT Secret',
    'JWT Secret key (leave blank to disable)' => 'JWT clé secrète (laisser en blanc pour désactiver)',
    'Share' => 'Partager',
    'View document' => 'Voir un document',
    'Document Editing Service address for internal requests from the server' => 'Adresse du service d’édition de document pour les demandes internes du serveur',
    'Server address for internal requests from the Document Editing Service' => 'Adresse du serveur pour les demandes internes du service d’édition de document',
    'Can use ONLYOFFICE' => 'Peut utiliser ONLYOFFICE',
    'Allows the user to use ONLYOFFICE.' => 'Permet à l\'utilisateur d\'utiliser ONLYOFFICE.',
];
