<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Criar</strong> documento',
    '<strong>ONLYOFFICE Docs</strong> not accessible.' => '<strong>ONLYOFFICE Docs</strong> não acessível.',
    '<strong>ONLYOFFICE Docs</strong> not configured yet.' => '<strong>ONLYOFFICE Docs</strong> não configurado.',
    '<strong>ONLYOFFICE Docs</strong> successfully connected! - Installed version: {version}' => '<strong>ONLYOFFICE Docs</strong> conectado com sucesso! - Versão instalada: {version}',
    '<strong>ONLYOFFICE - Docs</strong> module configuration' => '<strong>ONLYOFFICE - Docs</strong> Configuração de módulo',
    '<strong>Share</strong> document' => '<strong>Compartilhar</strong> documento',
    'Close' => 'Fechar',
    'Copy to clipboard' => 'Copiar para área de transferência',
    'Could not find requested file!' => 'Não foi possível encontrar o arquivo solicitado!',
    'Could not find shared file!' => 'Não foi possível encontrar o arquivo compartilhado!',
    'File read access denied!' => 'Acesso de leitura ao arquivo negado!',
    'File write access denied!' => 'Acesso de edição ao arquivo negado!',
    'Hostname' => 'Servidor',
    'Link for view only access' => 'Link para acesso apenas para visualização',
    'Link with enabled write access' => 'Link para acesso com permissão de edição',
    'Open the new document in the next step' => 'Abrir o novo documento no próximo passo',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Você pode simplesmente compartilhar esse documento usando um link direto. O usuário não precisa de uma conta válida na plataforma.',
    'e.g. http://documentserver' => 'e.g. http://documentserver',
    '<strong>Convert</strong> document' => '<strong>Converter</strong> documento',
    '<strong>ONLYOFFICE Docs</strong> invalid JWT token.' => '<strong>ONLYOFFICE Docs</strong> token JWT inválido.',
    'Convert document' => 'Converter documento',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Convertendo <strong>{oldFileName}</strong> para <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Criar documento <small>(Texto, Planilha, Apresentação)</small>',
    'Done!' => 'Feito!',
    'Edit document' => 'Editar documento',
    'Error:' => 'Erro:',
    'JWT Secret' => 'Segredo de JWT',
    'JWT Secret key (leave blank to disable)' => 'Chave secreta JWT (deixe em branco para desativar)',
    'Share' => 'Compartilhar',
    'View document' => 'Visualizar documento',
    'ONLYOFFICE Docs address for internal requests from the server' => 'Endereço do ONLYOFFICE Docs para pedidos internos do servidor',
    'Server address for internal requests from ONLYOFFICE Docs' => 'Endereço do servidor para pedidos internos do ONLYOFFICE Docs',
    'Can use ONLYOFFICE' => 'Pode usar ONLYOFFICE',
    'Allows the user to use ONLYOFFICE.' => 'Permite que o usuário use ONLYOFFICE.',
];
