<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Maak</strong> document',
    '<strong>ONLYOFFICE Docs</strong> not accessible.' => '<strong>ONLYOFFICE Docs</strong> is niet bereikbaar.',
    '<strong>ONLYOFFICE Docs</strong> not configured yet.' => '<strong>ONLYOFFICE Docs</strong> is nog niet geconfigureerd.',
    '<strong>ONLYOFFICE Docs</strong> successfully connected! - Installed version: {version}' => '<strong>ONLYOFFICE Docs</ strong> is succesvol aangesloten! - Geïnstalleerde versie: {versie}',
    '<strong>ONLYOFFICE - Docs</strong> module configuration' => '<strong>ONLYOFFICE - Docs</ strong> moduleconfiguratie',
    '<strong>Share</strong> document' => '<strong>Deel</strong> document',
    'Close' => 'Sluit',
    'Copy to clipboard' => 'Kopieer naar klembord',
    'Could not find requested file!' => 'Kan het gevraagde bestand niet vinden!',
    'Could not find shared file!' => 'Kan het gedeelde bestand niet vinden!',
    'File read access denied!' => 'Lees-toegang geweigerd!',
    'File write access denied!' => 'Schrijf-toegang geweigerd!',
    'Hostname' => 'Computernaam (Hostname)',
    'Link for view only access' => 'Link voor alleen lees-toegang',
    'Link with enabled write access' => 'Link voor schrijf-toegang',
    'Open the new document in the next step' => 'Open het nieuwe document in de volgende stap',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'U kunt dit document eenvoudig delen met een directe link. De gebruiker heeft geen geldig gebruikersaccount op het platform nodig.',
    'e.g. http://documentserver' => 'bijvoobeeld http://documentserver',
    '<strong>Convert</strong> document' => 'Document <strong>omzetten</strong>',
    '<strong>ONLYOFFICE Docs</strong> invalid JWT token.' => '<strong>ONLYOFFICE Docs</strong> invalid JWT token.',
    'Convert document' => 'Document omzetten',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Omzetten <strong>{oldFileName}</strong> naar <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Document maken <small>(Tekst, Spreadsheet, presentatie)</small>',
    'Done!' => 'Klaar!',
    'Edit document' => 'Document bewerken',
    'Error:' => 'Fout:',
    'JWT Secret' => 'JWT Geheim',
    'JWT Secret key (leave blank to disable)' => 'JWT Geheime sleutel (leeg laten om niet te te gebruiken)',
    'Share' => 'Delen',
    'View document' => 'Bekijk Document',
    'ONLYOFFICE Docs address for internal requests from the server' => 'Adres van de ONLYOFFICE Docs voor interne verzoeken van de server',
    'Server address for internal requests from ONLYOFFICE Docs' => 'Serveradres voor interne verzoeken van de ONLYOFFICE Docs',
    'Can use ONLYOFFICE' => 'Kan ONLYOFFICE gebruiken',
    'Allows the user to use ONLYOFFICE.' => 'Geeft de gebruiker toestemming om ONLYOFFICE te gebruiken.',
    'Form template' => 'Formulier sjabloon',
    'Fill in form in ONLYOFFICE' => 'Formulier invullen in ONLYOFFICE',
    'Please update ONLYOFFICE Docs to version 7.0 to work on fillable forms online' => 'Update ONLYOFFICE Docs naar versie 7.0 om online invulbare formulieren te kunnen gebruiken',
    'Disable certificate verification (insecure)' => 'Certificaatverificatie uitschakelen (onveilig)',
    'Not supported version' => 'Niet ondersteunde versie"',
    'The customization section allows personalizing the editor interface' => 'Met de aanpassingssectie kunt u de interface van de editor personaliseren',
    'Display Chat menu button' => 'Chat Menuknop weergeven',
    'Display the header more compact' => 'De koptekst compacter weergeven',
    'Display Feedback & Support menu button' => 'Menuknop Terugkoppeling & Ondersteuning weergeven',
    'Display Help menu button' => 'Menuknop Help weergeven',
    'Display monochrome toolbar header' => 'Toon de monochrome koptekst van de werkbalk',
    'Error when trying to connect ({error})' => 'Fout bij het verbinden ({error})',
    'Mixed Active Content is not allowed. HTTPS address for ONLYOFFICE Docs is required.' => 'Gemende Actieve Inhoud is niet toegestaan. HTTPS-adres voor ONLYOFFICE Docs is vereist.',
    'Open the file for editing (due to format restrictions, the data might be lost when saving to the formats from the list below)' => 'Open het bestand om het te bewerken (wegens formaatbeperkingen kunnen de gegevens verloren gaan bij het opslaan in de formaten van de onderstaande lijst)',
    'Connect to demo ONLYOFFICE Docs server' => 'Verbinden met de demo ONLYOFFICE Docs server',
    'This is a public test server, please do not use it for private sensitive data. The server will be available during a 30-day period.' => 'Dit is een openbare testserver, gelieve deze niet te gebruiken voor persoonlijke en vertrouwelijke gegevens. De server zal gedurende een periode van 30 dagen beschikbaar zijn.',
    'The 30-day test period is over, you can no longer connect to demo ONLYOFFICE Docs server.' => 'De 30-dagen proefperiode is voorbij, u kunt niet langer verbinding maken met demo ONLYOFFICE Docs server.',
    'Keep intermediate versions when editing (forcesave)' => 'Bewaar tussentijdse versies bij bewerken (forcesave)',
];
