<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => 'Dokument <strong>erstellen</strong> ',
    '<strong>ONLYOFFICE Docs</strong> not accessible.' => '<strong>ONLYOFFICE Docs</strong> nicht erreichbar',
    '<strong>ONLYOFFICE Docs</strong> not configured yet.' => '<strong>ONLYOFFICE Docs</strong> wurde noch nicht konfiguriert.',
    '<strong>ONLYOFFICE Docs</strong> successfully connected! - Installed version: {version}' => 'Erfolgreich mit dem <strong>ONLYOFFICE Docs</strong> verbunden! – Installierte Version: {version}',
    '<strong>ONLYOFFICE - Docs</strong> module configuration' => '<strong>ONLYOFFICE – Docs</strong> Modul-Konfiguration',
    '<strong>Share</strong> document' => 'Dokument <strong>teilen</strong>',
    'Close' => 'Schließen',
    'Copy to clipboard' => 'In die Zwischenablage kopieren',
    'Could not find requested file!' => 'Angeforderte Datei nicht gefunden!',
    'Could not find shared file!' => 'Geteilte Datei nicht gefunden!',
    'File read access denied!' => 'Lesezugriff wurde abgelehnt!',
    'File write access denied!' => 'Schreibzugriff wurde abgelehnt!',
    'Hostname' => 'Hostname',
    'Link for view only access' => 'Link für Lesezugriff',
    'Link with enabled write access' => 'Link mit aktiviertem Schreibzugriff',
    'Open the new document in the next step' => 'Öffne das neue Dokument im nächsten Schritt',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Du kannst dieses Dokument einfach über einen direkten Link teilen. Der Nutzer benötigt kein gültiges Benutzerkonto auf der Plattform.',
    'e.g. http://documentserver' => 'z.B. http://documentserver',
    '<strong>Convert</strong> document' => 'Dokument <strong>konvertieren</strong>',
    '<strong>ONLYOFFICE Docs</strong> invalid JWT token.' => '<strong>ONLYOFFICE Docs</strong> ungültiges JWT-Token.',
    'Convert document' => 'Dokument konvertieren',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Konvertieren <strong>{oldFileName}</strong> zu <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Dokument erstellen <small>(Text, Tabellenkalkulation, Präsentation)</small>',
    'Done!' => 'Fertig!',
    'Edit document' => 'Dokument bearbeiten',
    'Error:' => 'Fehler:',
    'JWT Secret' => 'JWT-Geheimnis',
    'JWT Secret key (leave blank to disable)' => 'JWT geheimer Schlüssel (zum Deaktivieren leer lassen)',
    'Share' => 'Freigeben',
    'View document' => 'Dokument anzeigen',
    'ONLYOFFICE Docs address for internal requests from the server' => 'Die Adresse von ONLYOFFICE Docs für interne Anforderungen vom Server',
    'Server address for internal requests from ONLYOFFICE Docs' => 'Serveradresse für interne Anforderungen  vom ONLYOFFICE Docs',
    'Can use ONLYOFFICE' => 'Kann ONLYOFFICE benutzen',
    'Allows the user to use ONLYOFFICE.' => 'Erlaubt diesem Benutzer Arbeit in ONLYOFFICE.',
    'Fill in form in ONLYOFFICE' => 'Formular in ONLYOFFICE ausfüllen',
    'Please update ONLYOFFICE Docs to version 7.0 to work on fillable forms online' => 'Für Online-Arbeit mit Formularen ist Version 7.0 von ONLYOFFICE Docs erforderlich',
    'Disable certificate verification (insecure)' => 'Zertifikatsüberprüfung deaktivieren (unsicher)',
    'Not supported version' => 'Nicht unterstützte Version',
    'The customization section allows personalizing the editor interface' => 'Die Anpassungssektion ermöglicht die Anpassung der Editoroberfläche',
    'Display Chat menu button' => 'Chat-Taste anzeigen',
    'Display the header more compact' => 'Kompakten Header anzeigen',
    'Display Feedback & Support menu button' => 'Feedback-& Support-Taste anzeigen',
    'Display Help menu button' => 'Hilfetaste anzeigen',
    'Display monochrome toolbar header' => 'Monochromen Kopfbereich der Symbolleiste anzeigen',
    'Error when trying to connect ({error})' => 'Fehler beim Anschließen ({error})',
    'Mixed Active Content is not allowed. HTTPS address for ONLYOFFICE Docs is required.' => 'Mixed Active Content ist nicht möglich. HTTPS-Adresse für ONLYOFFICE Docs ist erforderlich.',
    'Open the file for editing (due to format restrictions, the data might be lost when saving to the formats from the list below)' => 'Öffne die Datei zum Bearbeiten (aufgrund von Formateinschränkungen können die Daten beim Speichern in den Formaten aus der folgenden Liste verloren gehen)',
    'Connect to demo ONLYOFFICE Docs server' => 'Verbindung zu Demo ONLYOFFICE Docs Server herstellen',
    'This is a public test server, please do not use it for private sensitive data. The server will be available during a 30-day period.' => 'Dies ist ein öffentlicher Testserver. Bitte verwende beim Testen keine privaten sensiblen Daten. Der Server ist 30 Tage lang verfügbar.',
    'The 30-day test period is over, you can no longer connect to demo ONLYOFFICE Docs server.' => 'Der 30-tägige Testzeitraum ist abgelaufen. Du kannst keine Verbindung mehr zu Demo ONLYOFFICE Docs Server herstellen.',
    'Keep intermediate versions when editing (forcesave)' => 'Zwischenversionen bei der Bearbeitung aufbewahren (force save)',
    'Authorization header' => 'Authorization-Header',
    'Leave blank to use default header' => 'Leer lassen, um die standardmäßige Kopfzeile zu verwenden',
];
