<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Tạo</strong> tài liệu',
    '<strong>DocumentServer</strong> not accessible.' => '<strong>Máy chủ tài liệu</strong> không thể truy cập.',
    '<strong>DocumentServer</strong> not configured yet.' => '<strong>Máy chủ tài liệu</strong> chưa được cấu hình.',
    '<strong>DocumentServer</strong> successfully connected! - Installed version: {version}' => '<strong>Máy chủ tài liệu</strong> kết nối thành công! - Phiên bản: {version}',
    '<strong>ONLYOFFICE - DocumentServer</strong> module configuration' => 'Cấu hình module <strong>ONLYOFFICE - DocumentServer</strong>',
    '<strong>Share</strong> document' => '<strong>Chia sẻ</strong> tài liệu',
    'Close' => 'Đóng',
    'Copy to clipboard' => 'Copy vào clipboard',
    'Could not find requested file!' => 'Không thể tìm thấy file yêu cầu!',
    'Could not find shared file!' => 'Không thể tìm thấy file chia ser!',
    'File read access denied!' => 'Không có quyền đọc file!',
    'File write access denied!' => 'Không có quyền ghi file!',
    'Hostname' => 'Tên host',
    '<strong>Convert</strong> document' => '<strong>Chuyển đổi</strong> tài liệu',
    '<strong>DocumentServer</strong> invalid JWT token.' => '<strong>Máy chủ Tài liệu</strong> mã JWT không hợp lệ.',
    'Convert document' => 'Chuyển đổi tài liệu',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Chuyển đổi <strong>{oldFileName}</strong> thành <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Tạo tài liệu <small>(Văn bản, Bảng tính, Thuyết trình)</small>',
    'Done!' => 'Hoàn tất!',
    'Edit document' => 'Chỉnh sửa Tài liệu',
    'Error:' => 'Lỗi:',
    'JWT Secret' => 'Bí mật JWT',
    'JWT Secret key (leave blank to disable)' => 'Khóa bí mật JWT (để trống để tắt)',
    'Link for view only access' => 'Liên kết chỉ để xem',
    'Link with enabled write access' => 'Liên kết với quyền truy cập cho phép ghi',
    'Open the new document in the next step' => 'Mở tài liệu mới trong bước tiếp theo',
    'Share' => 'Chia sẻ',
    'View document' => 'Xem tài liệu',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Bạn có thể chia sẻ tài liệu này bằng cách sử dụng một liên kết trực tiếp. Người dùng không cần phải có một tài khoản người dùng hợp lệ trên nền tảng này.',
    'e.g. http://documentserver' => 'ví dụ: http://documentserver',
    'Document Editing Service address for internal requests from the server' => 'Địa chỉ Dịch Vụ Chỉnh Sửa Tài Liệu cho các yêu cầu nội bộ từ máy chủ',
    'Server address for internal requests from the Document Editing Service' => 'Địa chỉ máy chủ cho các yêu cầu nội bộ từ Dịch Vụ Chỉnh Sửa Tài Liệu',
    'Can use ONLYOFFICE' => 'Có thể sử dụng ONLYOFFICE',
    'Allows the user to use ONLYOFFICE.' => 'Cho phép người dùng sử dụng ONLYOFFICE.',
];
