<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Tạo</strong> tài liệu',
    '<strong>DocumentServer</strong> not accessible.' => '<strong>Máy chủ tài liệu</strong> không thể truy cập.',
    '<strong>DocumentServer</strong> not configured yet.' => '<strong>Máy chủ tài liệu</strong> chưa được cấu hình.',
    '<strong>DocumentServer</strong> successfully connected! - Installed version: {version}' => '<strong>Máy chủ tài liệu</strong> kết nối thành công! - Phiên bản: {version}',
    '<strong>OnlyOffice - DocumentServer</strong> module configuration' => 'Cấu hình module <strong>OnlyOffice - DocumentServer</strong>',
    '<strong>Share</strong> document' => '<strong>Chia sẻ</strong> tài liệu',
    'Close' => 'Đóng',
    'Copy to clipboard' => 'Copy vào clipboard',
    'Could not find requested file!' => 'Không thể tìm thấy file yêu cầu!',
    'Could not find shared file!' => 'Không thể tìm thấy file chia ser!',
    'File read access denied!' => 'Không có quyền đọc file!',
    'File write access denied!' => 'Không có quyền ghi file!',
    'Hostname' => 'Tên host',
    '<strong>Convert</strong> document' => '',
    '<strong>DocumentServer</strong> invalid JWT token.' => '',
    'Convert document' => '',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => '',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => '',
    'Done!' => '',
    'Edit document' => '',
    'Error:' => '',
    'JWT Secret' => '',
    'JWT Secret key (leave blank to disable)' => '',
    'Link for view only access' => '',
    'Link with enabled write access' => '',
    'Open the new document in the next step' => '',
    'Share' => '',
    'View document' => '',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => '',
    'e.g. http://documentserver' => '',
];
