<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => '<strong>Utwórz</strong> dokument',
    '<strong>ONLYOFFICE Docs</strong> not accessible.' => '<strong>ONLYOFFICE Docs</strong> niedostępny.',
    '<strong>ONLYOFFICE Docs</strong> not configured yet.' => '<strong>ONLYOFFICE Docs</strong> jeszcze nie skonfigurowany.',
    '<strong>ONLYOFFICE Docs</strong> successfully connected! - Installed version: {version}' => '<strong>ONLYOFFICE Docs</strong> Połączono - Zainstalowana wersja: {version}',
    '<strong>ONLYOFFICE - Docs</strong> module configuration' => '<strong>ONLYOFFICE - Docs</strong> konfiguracja modułu',
    '<strong>Share</strong> document' => '<strong>Udostępnij</strong> dokument',
    'Close' => 'Zamknij',
    'Copy to clipboard' => 'Kopiuj do schowka',
    'Could not find requested file!' => 'Nie znaleziono wybranego pliku!',
    'Could not find shared file!' => 'Nie znaleziono udostępnionego pliku!',
    'File read access denied!' => 'Odmowa dostępu do odczytu pliku!',
    'File write access denied!' => 'Odmowa dostępu do zapisu pliku!',
    'Hostname' => 'Nazwa Hosta',
    'Link for view only access' => 'Odnośnik z dostępem tylko do odczytu',
    'Link with enabled write access' => 'Odnośnik z dostępem do zapisu',
    'Open the new document in the next step' => 'Otwórz nowy dokument w następnym kroku',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Możesz udostępnić ten dokument używając bezpośredniego odnośnika. Użytkownik nie musi posiadać konta na tej platformie.',
    'e.g. http://documentserver' => 'np. http://documentserver',
    '<strong>Convert</strong> document' => '<strong>Konwertuj</strong> dokument',
    '<strong>ONLYOFFICE Docs</strong> invalid JWT token.' => '<strong>ONLYOFFICE Docs</strong> nieprawidłowy token JWT.',
    'Convert document' => 'Konwertuj dokument',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => 'Konwertowanie <strong>{oldFileName}</strong> do <strong>{newFileName}</strong>..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Utwórz dokument <small>(Tekst, Arkusz kalkulacyjny, Prezentacja)</small>',
    'Done!' => 'Gotowe!',
    'Edit document' => 'Edytuj dokument',
    'Error:' => 'Błąd:',
    'JWT Secret' => 'JWT Secret',
    'JWT Secret key (leave blank to disable)' => 'JWT Secret key (pozostaw puste, aby wyłączyć)',
    'Share' => 'Udostępnij',
    'View document' => 'Wyświetl dokument',
    'ONLYOFFICE Docs address for internal requests from the server' => 'Adres ONLYOFFICE Docs dla zapytań wewnętrznych',
    'Server address for internal requests from ONLYOFFICE Docs' => 'Adres serwera dla zapytań wewnętrznych z ONLYOFFICE Docs',
    'Can use ONLYOFFICE' => 'Może korzystać z ONLYOFFICE',
    'Allows the user to use ONLYOFFICE.' => 'Zezwala użytkownikowi na korzystanie z ONLYOFFICE.',
    'Form template' => 'Szablon formularza',
    'Fill in form in ONLYOFFICE' => 'Wypełnić formularz w ONLYOFFICE',
    'Please update ONLYOFFICE Docs to version 7.0 to work on fillable forms online' => 'Zaktualizuj ONLYOFFICE Docs do wersji 7.0, aby działały w formularzach do wypełniania online',
    'Disable certificate verification (insecure)' => 'Wyłącz weryfikację certyfikatu (niebezpieczne)',
    'The customization section allows personalizing the editor interface' => 'Ta sekcja pozwala na personalizację interefejsu edytorów',
    'Display Chat menu button' => 'Wyświetl menu Czatu',
    'Display the header more compact' => 'Wyświetlaj bardziej kompaktowy nagłówek',
    'Display Feedback & Support menu button' => 'Wyświetlaj Opinie i Support',
    'Display Help menu button' => 'Wyświetlaj menu pomocy',
    'Display monochrome toolbar header' => 'Wyświetl monochromatyczny nagłówek paska narzędzi',
    'Error when trying to connect ({error})' => 'Błąd przy próbie połączenia ({error})',
    'Mixed Active Content is not allowed. HTTPS address for ONLYOFFICE Docs is required.' => 'Aktywna Zawartość Mieszana nie jest dozwolona. Adres HTTPS jest wymagany dla ONLYOFFICE Docs.',
    'Open the file for editing (due to format restrictions, the data might be lost when saving to the formats from the list below)' => 'Otwórz plik do edycji (ze względu na ograniczenia formatów, dane mogą zostac utracone przy zapisie do formatów podanych poniżej)',
    'Connect to demo ONLYOFFICE Docs server' => 'Połącz się z serwerem demo ONLYOFFICE Docs',
    'This is a public test server, please do not use it for private sensitive data. The server will be available during a 30-day period.' => 'To jest publiczny testowy serwer, proszę nie używać go do prywatnych danych. Serwer będzie dostępny przez 30 dni.',
    'The 30-day test period is over, you can no longer connect to demo ONLYOFFICE Docs server.' => 'Upłyneło 30 dni, nie możesz się już łączyć z serwerem demo.',
];
