<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> document' => 'Dokumentum <strong>létrehozása</strong>',
    '<strong>DocumentServer</strong> not accessible.' => '<strong>DocumentServer</strong> nem elérhető.',
    '<strong>DocumentServer</strong> not configured yet.' => '<strong>DocumentServer</strong> még nincs konfigurálva.',
    '<strong>DocumentServer</strong> successfully connected! - Installed version: {version}' => '<strong>DocumentServer</strong> sikeresen kapcsolódott! - Telepített verzió: {version}',
    '<strong>ONLYOFFICE - DocumentServer</strong> module configuration' => '<strong>ONLYOFFICE - DocumentServer</strong> modul konfiguráció',
    '<strong>Share</strong> document' => 'Dokumentum <strong>megosztása</strong>',
    'Close' => 'Bezárás',
    'Copy to clipboard' => 'Másolás a vágólapra',
    'Could not find requested file!' => 'A kért fájl nem található!',
    'Could not find shared file!' => 'A megosztott fájl nem található!',
    'File read access denied!' => 'Fájl olvasása megtagadva!',
    'File write access denied!' => 'Fájl írása megtagadva!',
    'Hostname' => 'Hosztnév',
    'Link for view only access' => 'Hivatkozás csak megtekintéshez',
    'Link with enabled write access' => 'Hivatkozás íráshoz',
    'Open the new document in the next step' => 'A következő lépésben nyissa meg a dokumentumot',
    'You can simply share this document using a direct link. The user does not need an valid user account on the platform.' => 'Egyszerűen megoszthatod ezt a dokumentumot közvetlen hivatkozás használatával. A felhasználónak nem kell érvényes felhasználói fiókkal rendelkeznie a platformon.',
    'e.g. http://documentserver' => 'pl. http://documentserver',
    '<strong>Convert</strong> document' => 'Dokumentum <strong>konvertálása</strong>',
    '<strong>DocumentServer</strong> invalid JWT token.' => '<strong>DocumentServer</strong> érvénytelen JWT  jelkép.',
    'Convert document' => 'Dokumentum konvertálása',
    'Converting <strong>{oldFileName}</strong> to <strong>{newFileName}</strong>..' => '<strong>{oldFileName}</strong> konvertálása <strong>{newFileName}</strong>-re..',
    'Create document <small>(Text, Spreadsheet, Presentation)</small>' => 'Dokumentum készítése <small>(Szöveg,  Táblázatkezelő, Prezentáció)</small>',
    'Done!' => 'Kész!',
    'Edit document' => 'Dokumentum szerkesztése',
    'Error:' => 'Hiba:',
    'JWT Secret' => 'JWT Titok',
    'JWT Secret key (leave blank to disable)' => 'JWT Titok kulcs (hagyd üresen a kikapcsoláshoz)',
    'Share' => 'Megosztás',
    'View document' => 'Dokumentum megnézése',
    'Document Editing Service address for internal requests from the server' => 'Dokumentumszerkesztő szolgáltatás elérési címe szerveroldali belső lekérésekhez',
    'Server address for internal requests from the Document Editing Service' => 'Szerver elérési címe a Dokumentumszerkesztő szolgáltatástól érkező belső lekérésekhez',
];
